CREATE TABLE IF NOT EXISTS hits (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
    app VARCHAR(255),
    uri VARCHAR(255),
    ip VARCHAR(255),
    time_stamp TIMESTAMP WITHOUT TIME ZONE);